### ISSUE TITLE
The locale file needs update

### ISSUE THREAD

**Issue by Akryum** [SevenOutman/vue-cli-locale-zh#1]
The locale structure has changed to respect Reverse Domain Name Notation.

See:
- https://twitter.com/Akryum/status/1017824851564822529
- https://github.com/vuejs/vue-cli/issues/1915#issuecomment-407056725

**Comment by SevenOutman** [comment]
@Akryum Thanks for pointing out!

BTW I notice that UI looks for `zh-CN` locale pack in the first place, getting a 404 error, then fallback to `zh`.
![image](https://user-images.githubusercontent.com/8225666/43082475-ba03ffda-8ec6-11e8-98a3-b2bc2e36506f.png)

Should I publish another one with that name, or change this existing package's name? Or just leave it as it is?

**Comment by Akryum** [comment]
It means you have `zh-CN` first in your browser settings, that's all. The UI will try all of them and eventually fallback to english.
